---
title: "ineficiencia según modalidad"
author: "Charles Gabriel Sánchez Salas"
date: "2024-06-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rio)
library(ggplot2)
library(ggcorrplot)
library(reticulate)
use_python("C:/Users/Charles/anaconda3")
```

```{r}
rm(list = ls())
```

```{r}
inefilink= "https://github.com/bocchienjoyer/MaGODllanes/raw/main/ProyectoMagaDeidad/datita/year_mod_obras_long.pkl"
```


```{r}
pd<-import("pandas")
```

```{r}
inefistats<- pd$read_pickle(inefilink)
```

```{r}
str(inefistats)
```

```{r}
graf1= ggplot(data=inefistats,
               aes(x=ano,y=value,color=modalidad_ejecucion)) + geom_smooth(se=TRUE, method = "loess")+ scale_color_manual(values = c("Administración directa"= "red", "Contrata"= "yellow", "Otros"="blue")) + theme_light() +
  labs(title = "Evolución de la ineficiencia de las obras según modalidad",
       x="Año",
       y="Puntaje promdio IRI",
       color="Modalidad de ejecución")
    scale_y_log10(labels=scales::comma)
graf1 +    
    geom_smooth()  + 
    facet_grid(variable~.,scales = 'free_y') 
```


